#pragma once

// ──── HexHound - Where a worn cosmetic sits on the pet ───────
//
// GENERATED by scripts/gen_wear_anchors.py. Do not edit by hand.
//
// Thousandths of the sprite's own box, which is the whole source canvas:
// gen_hd_sprites.py resizes 400x400 to the target size rather than cropping
// to the figure, so a fraction of the canvas is the same fraction of the
// sprite at every size on every panel. One table serves a 24 px pet on a
// T-Dongle and a 320 px hero shot on the T-RGB.
//
// The table is AUTHORED and then verified against the silhouette, not
// derived from it. Four automatic heuristics were tried and each placed at
// least one anchor visibly wrong; the five characters have too little
// anatomy in common. The script asserts every anchor lands on the figure and
// every box fits the canvas, and --preview renders the overlays onto all
// five stages so the placement can be checked by looking at it.
//
// `w` is the side of the SQUARE an overlay is drawn into, not the width of
// the body part. It is larger than the part on purpose: a cap is authored in
// the upper third of its square and goggles across the middle of theirs, so
// two items that share one anchor still sit in two different places.

#include <stdint.h>
#include "../config.h"   // PetStage

// Thousandths. Named so a reader cannot mistake these for pixels.
#define WEAR_ANCHOR_UNIT 1000

struct WearAnchorPoint {
    int16_t cx;    // centre of the anchor across the sprite box
    int16_t cy;    // centre of the anchor down the sprite box
    int16_t w;     // side of the square the overlay is drawn into
};

struct WearStageAnchors {
    WearAnchorPoint head;
    WearAnchorPoint neck;
};

// Indexed by (PetStage - STAGE_EGG); PetStage starts at 1, not 0, so the
// subtraction is not optional and wearAnchorsFor() is the only place allowed
// to do it.
static const WearStageAnchors WEAR_ANCHORS[] = {
    // egg  // no head or neck; unreachable, every worn recipe gates later
    {{  500,  300,  300 }, {  500,  480,  300 }},
    // pup
    {{  500,  250,  300 }, {  500,  490,  300 }},
    // beast
    {{  500,  185,  195 }, {  500,  470,  330 }},
    // gremlin
    {{  505,  255,  330 }, {  505,  620,  300 }},
    // sentinel
    {{  500,  215,  265 }, {  500,  355,  360 }},
};

static_assert(sizeof(WEAR_ANCHORS) / sizeof(WEAR_ANCHORS[0]) ==
                  (size_t)(STAGE_SENTINEL - STAGE_EGG + 1),
              "WEAR_ANCHORS must have one row per PetStage; a stage was added "
              "without re-running scripts/gen_wear_anchors.py");

// The only place the stage-to-index subtraction happens. Clamps rather than
// trusting the caller: this is read by the renderer on every frame, and a
// stage byte from a corrupt save must not index off the front of the table.
inline const WearStageAnchors& wearAnchorsFor(PetStage stage) {
    int i = (int)stage - (int)STAGE_EGG;
    const int n = (int)(sizeof(WEAR_ANCHORS) / sizeof(WEAR_ANCHORS[0]));
    if (i < 0) i = 0;
    if (i >= n) i = n - 1;
    return WEAR_ANCHORS[i];
}
