#pragma once

#include <stdint.h>

// ── HexHound - Trusted Content Signing Keys ──────────────────────
//
// GENERATED FILE. Regenerate with:
//     python scripts/sign_content_pack.py --gen-key
//
// These are PUBLIC keys. Nothing secret is in this file and nothing secret is
// ever allowed in it. The private halves live outside the repository; see
// docs/p3w2-wiring.md.
//
// A pack is accepted only when it is signed by a key in this list. Adding a
// key here is a firmware change, which is the point: content is data, but who
// may author content is code.
//
// ── THIS IS A DEVELOPMENT KEY ─────────────────────────────────────────────
// The key below was generated by a developer, on a developer machine, and its
// private half is sitting in a gitignored file on that machine. It is fine for
// bring-up and for the simulator. It must be replaced before any build is
// handed to anyone, because "the signature checks out" means nothing when the
// signing key is that easy to reach.

// Machine-readable provenance, read by the publish gate in
// scripts/deploy_web_flasher.py and not by the firmware. It compiles to
// nothing and exists so a tool can answer "is this a release key?" instead of
// a human having to notice a comment. An ABSENT define counts as development,
// because unknown provenance is not release provenance.
#define CONTENT_KEY_PROVENANCE_DEVELOPMENT 1

#define CONTENT_TRUSTED_KEY_COUNT 1

// Key id f4c33e39 (first 4 bytes of SHA-512 of the key below). The id selects which
// key to try; it is not a credential and is never treated as one.
static const uint8_t CONTENT_TRUSTED_KEYS[CONTENT_TRUSTED_KEY_COUNT][32] = {
  {
    0xa6, 0xaf, 0x1d, 0xa2, 0x05, 0x1e, 0x2e, 0x79,
    0x6c, 0x23, 0x2a, 0x90, 0xed, 0x26, 0x24, 0xa3,
    0xfe, 0x70, 0x2f, 0x16, 0x69, 0x25, 0x1e, 0xef,
    0x30, 0x2a, 0x14, 0xe8, 0x9c, 0xd8, 0x66, 0x2e,
  }
};
