#pragma once

#include <stdint.h>

// ── HexHound - Trusted Content Signing Keys ──────────────────────
//
// GENERATED FILE. Regenerate with:
//     python scripts/sign_content_pack.py --gen-key
//
// These are PUBLIC keys. Nothing secret is in this file and nothing secret is
// ever allowed in it. The private halves live outside the repository; see
// docs/p3w2-wiring.md.
//
// A pack is accepted only when it is signed by a key in this list. Adding a
// key here is a firmware change, which is the point: content is data, but who
// may author content is code.
//
// ── THIS IS A DEVELOPMENT KEY ─────────────────────────────────────────────
// The key below was generated by a developer, on a developer machine, and its
// private half is sitting in a gitignored file on that machine. It is fine for
// bring-up and for the simulator. It must be replaced before any build is
// handed to anyone, because "the signature checks out" means nothing when the
// signing key is that easy to reach.

// Machine-readable provenance, read by the publish gate in
// scripts/deploy_web_flasher.py and not by the firmware. It compiles to
// nothing and exists so a tool can answer "is this a release key?" instead of
// a human having to notice a comment. An ABSENT define counts as development,
// because unknown provenance is not release provenance.
#define CONTENT_KEY_PROVENANCE_DEVELOPMENT 0

#define CONTENT_TRUSTED_KEY_COUNT 1

// Key id 4b6b07cf (first 4 bytes of SHA-512 of the key below). The id selects which
// key to try; it is not a credential and is never treated as one.
static const uint8_t CONTENT_TRUSTED_KEYS[CONTENT_TRUSTED_KEY_COUNT][32] = {
  {
    0xac, 0x3a, 0x64, 0x0a, 0x8d, 0xbf, 0xd7, 0xf3,
    0xca, 0x01, 0x8f, 0x22, 0x59, 0x90, 0xbe, 0xfa,
    0xe7, 0xce, 0x5d, 0x11, 0xc4, 0x3a, 0xb1, 0x93,
    0x9d, 0x50, 0x97, 0xbb, 0xd7, 0x38, 0xdf, 0xd9,
  }
};
