#!/usr/bin/env python3
"""Turn a captured walk into a C header fixture for the native tests.

    python scripts/gen_step_fixture.py <capture.csv> --counted 118 \
        --walk-end-ms 100000 --out test/test_roam/walk_fixture.h

Emitted as source rather than read from disk at test time, matching how the OTA
fixtures work: a native test that depends on a file path is fragile about the
working directory, and a fixture that can go missing turns a regression test into
a silent skip.

The point of the fixture is that the step detector's calibration was fitted to ONE
real counted walk. Without this, that fitting is a number in a commit message that
nothing enforces; with it, any future change to the detector or its constants has
to keep agreeing with a real pocket.
"""

import argparse
import os


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("capture")
    ap.add_argument("--counted", type=int, required=True)
    ap.add_argument("--walk-end-ms", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--note", default="")
    # One walk is a calibration; two walks are a check on it. The macro and array
    # names are prefixed so a second capture can sit beside the first in the same
    # translation unit rather than replacing it - a fixture that gets overwritten
    # every time someone goes for a walk is not a regression test.
    # The noise floor a capture was taken through is part of what it proves, so
    # it is recorded rather than assumed. A jacket and a trouser pocket damp a
    # footfall differently and a fixture that claims the wrong one would send the
    # next person fitting constants to a carry that never happened.
    ap.add_argument("--carry", default="a trouser pocket")
    ap.add_argument("--prefix", default="WALK",
                    help="identifier stem: WALK -> WALK_FIXTURE_*/kWalk*, "
                         "WALK2 -> WALK2_FIXTURE_*/kWalk2*")
    args = ap.parse_args()

    macro = f"{args.prefix}_FIXTURE"
    arr = "k" + args.prefix.capitalize()

    rows = []
    device_steps = None
    with open(args.capture, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            if line.startswith("#"):
                if "device_detected_steps=" in line:
                    device_steps = int(line.split("device_detected_steps=")[1].split()[0])
                continue
            t, ax, ay, az = (int(x) for x in line.split(","))
            rows.append((t, ax, ay, az))

    if not rows:
        raise SystemExit("no samples parsed")

    # Time is delta-encoded, in uint16 rather than uint8. That is not cosmetic:
    # the first real capture had four ~411 ms stalls where a blocking SPIFFS
    # autosave starved the step sampler, and a byte-wide delta would have silently
    # misrepresented them. Those stalls are part of what the fixture must preserve,
    # because they are why the detector undercounts.
    deltas = []
    prev = rows[0][0]
    for i, (t, _, _, _) in enumerate(rows):
        d = 0 if i == 0 else t - prev
        if d > 65535:
            raise SystemExit(f"sample {i} has a {d} ms gap, too large even for "
                             f"uint16; look at the capture, do not widen this")
        deltas.append(d)
        prev = t

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as out:
        out.write("#pragma once\n\n")
        out.write("// GENERATED by scripts/gen_step_fixture.py - do not edit.\n")
        out.write("//\n")
        out.write("// A REAL counted walk, captured on the Waveshare 1.28 round board\n")
        out.write(f"// carried in {args.carry}, by the diagnostic build\n")
        out.write("// waveshare-esp32-s3-lcd-128-stepcap.\n")
        out.write("//\n")
        if args.note:
            for l in args.note.splitlines():
                out.write(f"// {l}".rstrip() + "\n")
            out.write("//\n")
        out.write("// This exists because the detector's constants were fitted to this one\n")
        out.write("// walk. Without it that fitting is only a number in a commit message.\n")
        out.write("// Synthetic waveforms CANNOT replace it: a clean spike clears every\n")
        out.write("// threshold, so every candidate parameter set scores identically on\n")
        out.write("// synthetic input. Only a real noise floor discriminates.\n\n")
        out.write(f"#define {macro}_SAMPLES      {len(rows)}\n")
        out.write(f"#define {macro}_COUNTED      {args.counted}\n")
        out.write(f"#define {macro}_WALK_END_MS  {args.walk_end_ms}\n")
        if device_steps is not None:
            out.write(f"#define {macro}_DEVICE_STEPS {device_steps}\n")
        out.write("\n")
        out.write("// dt_ms (delta), ax, ay, az - all milli-g\n")
        out.write(f"static const unsigned short {arr}Dt[{macro}_SAMPLES] = {{\n")
        for i in range(0, len(deltas), 24):
            out.write("    " + ",".join(str(d) for d in deltas[i:i + 24]) + ",\n")
        out.write("};\n\n")
        for name, idx in ((f"{arr}Ax", 1), (f"{arr}Ay", 2), (f"{arr}Az", 3)):
            out.write(f"static const short {name}[{macro}_SAMPLES] = {{\n")
            vals = [r[idx] for r in rows]
            for i in range(0, len(vals), 16):
                out.write("    " + ",".join(str(v) for v in vals[i:i + 16]) + ",\n")
            out.write("};\n\n")

    size = os.path.getsize(args.out)
    print(f"wrote {args.out} ({size//1024} KB, {len(rows)} samples, "
          f"counted={args.counted}, walk_end={args.walk_end_ms} ms)")


if __name__ == "__main__":
    main()
