#pragma once

#include <stdint.h>

// ── HexHound - Trusted OTA Signing Keys ──────────────────────────
//
// GENERATED FILE. Regenerate with:
//     python scripts/sign_ota_image.py --gen-key
//
// These are PUBLIC keys. Nothing secret is in this file and nothing secret is
// ever allowed in it.
//
// SEPARATE FROM THE CONTENT PACK KEY, deliberately. A leaked content key lets
// somebody write dialogue; a leaked firmware key lets somebody own the device.
// Different blast radius, so different custody and different rotation.
//
// An image is accepted only when it is signed by a key in this list. Adding a
// key here is a firmware change, which is the point: who may replace this
// firmware is not data.
//
// ── THIS IS A DEVELOPMENT KEY ─────────────────────────────────────────────
// Generated by a developer, on a developer machine, with its private half in
// a gitignored file on that machine. Fine for bring-up. It MUST be replaced
// before any build reaches anybody, because "the signature checks out" means
// nothing when the signing key is that easy to reach. An OTA key is the most
// valuable key in this project: it authorises replacing the firmware.

// Machine-readable provenance. Read by the publish gate in
// scripts/deploy_web_flasher.py, NOT by the firmware: it compiles to nothing,
// costs zero bytes, and exists so that "is this a release key?" is a question
// a tool can answer instead of a comment a human has to notice.
//
// 1 means the private half was generated by whoever ran --gen-key, onto that
// machine's disk. 0 means a release public key was installed with
// --set-release-pubkey and its private half has never been in this repository.
// An ABSENT define is treated as 1 by the gate, because unknown provenance is
// not release provenance.
#define OTA_KEY_PROVENANCE_DEVELOPMENT 0

#define OTA_TRUSTED_KEY_COUNT 1

// Key id 443c5bc9 (first 4 bytes of SHA-512 of the key below). The id selects
// which key to try; it is a selector and never a credential.
static const uint8_t OTA_TRUSTED_KEY_IDS[OTA_TRUSTED_KEY_COUNT][4] = {
  { 0x44, 0x3c, 0x5b, 0xc9 },
};

static const uint8_t OTA_TRUSTED_KEYS[OTA_TRUSTED_KEY_COUNT][32] = {
  {
    0xd9, 0xcc, 0xf1, 0xb6, 0x8a, 0x28, 0xed, 0x1d,
    0x35, 0x01, 0xa9, 0xc1, 0x10, 0x81, 0x47, 0x43,
    0x4c, 0x62, 0x70, 0x38, 0x9b, 0x71, 0xa4, 0xd9,
    0x3e, 0x14, 0x79, 0xe9, 0x52, 0x0e, 0xf3, 0x39
  },
};
