#pragma once

#include <stdint.h>

// ── HexHound - Trusted OTA Signing Keys ──────────────────────────
//
// GENERATED FILE. Regenerate with:
//     python scripts/sign_ota_image.py --gen-key
//
// These are PUBLIC keys. Nothing secret is in this file and nothing secret is
// ever allowed in it.
//
// SEPARATE FROM THE CONTENT PACK KEY, deliberately. A leaked content key lets
// somebody write dialogue; a leaked firmware key lets somebody own the device.
// Different blast radius, so different custody and different rotation.
//
// An image is accepted only when it is signed by a key in this list. Adding a
// key here is a firmware change, which is the point: who may replace this
// firmware is not data.
//
// ── THIS IS A DEVELOPMENT KEY ─────────────────────────────────────────────
// Generated by a developer, on a developer machine, with its private half in
// a gitignored file on that machine. Fine for bring-up. It MUST be replaced
// before any build reaches anybody, because "the signature checks out" means
// nothing when the signing key is that easy to reach. An OTA key is the most
// valuable key in this project: it authorises replacing the firmware.

// Machine-readable provenance. Read by the publish gate in
// scripts/deploy_web_flasher.py, NOT by the firmware: it compiles to nothing,
// costs zero bytes, and exists so that "is this a release key?" is a question
// a tool can answer instead of a comment a human has to notice.
//
// 1 means the private half was generated by whoever ran --gen-key, onto that
// machine's disk. 0 means a release public key was installed with
// --set-release-pubkey and its private half has never been in this repository.
// An ABSENT define is treated as 1 by the gate, because unknown provenance is
// not release provenance.
#define OTA_KEY_PROVENANCE_DEVELOPMENT 1

#define OTA_TRUSTED_KEY_COUNT 1

// Key id de895885 (first 4 bytes of SHA-512 of the key below). The id selects
// which key to try; it is a selector and never a credential.
static const uint8_t OTA_TRUSTED_KEY_IDS[OTA_TRUSTED_KEY_COUNT][4] = {
  { 0xde, 0x89, 0x58, 0x85 },
};

static const uint8_t OTA_TRUSTED_KEYS[OTA_TRUSTED_KEY_COUNT][32] = {
  {
    0xfe, 0x80, 0xe6, 0xa3, 0xb1, 0x52, 0x5b, 0x34,
    0x3b, 0x84, 0x93, 0x44, 0x3b, 0x8f, 0x0d, 0xbe,
    0x77, 0x22, 0x1c, 0x70, 0x38, 0x53, 0x0a, 0xa5,
    0xd9, 0x80, 0x09, 0x79, 0x58, 0xa0, 0x3d, 0x7c
  },
};
